### ISSUE TITLE
Adding the prior hessian twice

### ISSUE THREAD

**Issue by AHsu98** [zhengp0/regmod#72]
We're adding the gaussian prior hess here: https://github.com/ihmeuw-msca/regmod/blob/7fd61b3c7416cf385059e8cd43b3c3f18cb47d94/src/regmod/models/model.py#L515
and here:
https://github.com/ihmeuw-msca/regmod/blob/7fd61b3c7416cf385059e8cd43b3c3f18cb47d94/src/regmod/models/model.py#L492C15-L492C15

And then these matrices are being multiplied together:
https://github.com/ihmeuw-msca/regmod/blob/7fd61b3c7416cf385059e8cd43b3c3f18cb47d94/src/regmod/models/model.py#L144-L146
This doesn't seem right?

It should be J * (HL + HP)^-1 * J^T, right not it looks like we're doing (J.T * J + HP) * (HL+HP)^-2 * (J.T * J +HP) where HL is hessian of the log likelihood and HP is the hessian of the log prior.

**Comment by zhengp0** [comment]
Hi @AHsu98! I think we had this discussion offline, this is sandwich estimation, we try to get variance covariate matrix roughly the order of inverse of hessian but at the same time incorporate the residual information :) I will close this issue. But please let me know if there are further concerns!
